group_new:
    path:     /new_group
    defaults: { _controller: "ShopAdminBundle:Menu:newGroup" }

subgroup_new:
    path:     /new_subgroup
        defaults: { _controller: "ShopAdminBundle:Menu:newSubgroup" }